import React from 'react';
import ReactDOM from 'react-dom';
import './index.css';
import {BrowserRouter} from "react-router-dom";
import App from './App';
import reportWebVitals from './reportWebVitals';

ReactDOM.render(
  <BrowserRouter >
    <App />
  </BrowserRouter >
,
  document.getElementById('root')
);


reportWebVitals();













// <option value='New-Caledonia' />
// <option value='India' />
// <option value='Micronesia' />
// <option value='Montserrat' />
// <option value='Anguilla' />
// <option value='Falkland-Islands' />
// <option value='Solomon-Islands' />
// <option value='Marshall-Islands' />
// <option value='Samoa' />
// <option value='Vatican-City' />
// <option value='Tanzania' />
// <option value='Wallis-and-Futuna' />
// <option value='Grenada' />
// <option value='Cayman-Islands' />
// <option value='Diamond-Princess' />
// <option value='MS-Zaandam' />
// <option value='Macao' />
// <option value='Western-Sahara' />
// <option value='Saint-Helena' />
// <option value='Vanuatu' />
// <option value='Dominica' />
// <option value='Faeroe-Islands' />
// <option value='Saint-Kitts-and-Nevis' />
// <option value='Brunei' />
// <option value='Saint-Pierre-Miquelon' />
// <option value='Greenland' />
// <option value='China' />
// <option value='Laos' />
// <option value='St-Barth' />
// <option value='Lesotho' />
// <option value='Gibraltar' />
// <option value='Taiwan' />
// <option value='Turks-and-Caicos' />
// <option value='Congo' />
// <option value='Yemen' />
// <option value='Djibouti' />
// <option value='Iceland' />
// <option value='Hong-Kong' />
// <option value='Mauritius' />
// <option value='Benin' />
// <option value='Timor-Leste' />
// <option value='Malta' />
// <option value='Syria' />
// <option value='Eritrea' />
// <option value='Mayotte' />
// <option value='Seychelles' />
// <option value='Andorra' />
// <option value='Fiji' />
// <option value='Chad' />
// <option value='Sao-Tome-and-Principe' />
// <option value='Saint-Martin' />
// <option value='CAR' />
// <option value='Antigua-and-Barbuda' />
// <option value='Gabon' />
// <option value='Sierra-Leone' />
// <option value='Comoros' />
// <option value='Bahamas' />
// <option value='Liechtenstein' />
// <option value='St-Vincent-Grenadines' />
// <option value='R&amp;eacute;union' />
// <option value='Cabo-Verde' />
// <option value='French-Guiana' />
// <option value='Suriname' />
// <option value='Equatorial-Guinea' />
// <option value='Mauritania' />
// <option value='Guyana' />
// <option value='Eswatini' />
// <option value='Haiti' />
// <option value='French-Polynesia' />
// <option value='Guadeloupe' />
// <option value='Somalia' />
// <option value='Mali' />
// <option value='Togo' />
// <option value='Tajikistan' />
// <option value='Belize' />
// <option value='Burkina-Faso' />
// <option value='Martinique' />
// <option value='Cura&amp;ccedil;ao' />
// <option value='Aruba' />
// <option value='South-Sudan' />
// <option value='Trinidad-and-Tobago' />
// <option value='Nicaragua' />
// <option value='Gambia' />
// <option value='Channel-Islands' />
// <option value='Burundi' />
// <option value='Saint-Lucia' />
// <option value='San-Marino' />
// <option value='Niger' />
// <option value='Barbados' />
// <option value='Guinea-Bissau' />
// <option value='Sint-Maarten' />
// <option value='Monaco' />
// <option value='Bermuda' />
// <option value='Bhutan' />
// <option value='Caribbean-Netherlands' />
// <option value='British-Virgin-Islands' />
// <option value='Guinea' />
// <option value='Liberia' />
// <option value='Papua-New-Guinea' />
// <option value='Australia' />
// <option value='New-Zealand' />
// <option value='Isle-of-Man' />
// <option value='Kyrgyzstan' />
// <option value='Uzbekistan' />
// <option value='El-Salvador' />
// <option value='Cambodia' />
// <option value='Nigeria' />
// <option value='Norway' />
// <option value='Armenia' />
// <option value='Estonia' />
// <option value='Cameroon' />
// <option value='Latvia' />
// <option value='Finland' />
// <option value='Afghanistan' />
// <option value='Libya' />
// <option value='Singapore' />
// <option value='Qatar' />
// <option value='Senegal' />
// <option value='Bahrain' />
// <option value='Slovenia' />
// <option value='Bosnia-and-Herzegovina' />
// <option value='Namibia' />
// <option value='Botswana' />
// <option value='Maldives' />
// <option value='Myanmar' />
// <option value='Luxembourg' />
// <option value='Moldova' />
// <option value='Cuba' />
// <option value='Zambia' />
// <option value='Mozambique' />
// <option value='Uganda' />
// <option value='DRC' />
// <option value='Albania' />
// <option value='Montenegro' />
// <option value='Cyprus' />
// <option value='Madagascar' />
// <option value='Kenya' />
// <option value='North-Macedonia' />
// <option value='Ivory-Coast' />
// <option value='Angola' />
// <option value='Jamaica' />
// <option value='Sudan' />
// <option value='Malawi' />
// <option value='Zimbabwe' />
// <option value='Rwanda' />
// <option value='Algeria' />
// <option value='Ghana' />
// <option value='S-Korea' />
// <option value='Vietnam' />
// <option value='Mongolia' />
// <option value='Belgium' />
// <option value='Israel' />
// <option value='Belarus' />
// <option value='Guatemala' />
// <option value='Hungary' />
// <option value='Egypt' />
// <option value='Georgia' />
// <option value='Czechia' />
// <option value='Lithuania' />
// <option value='Philippines' />
// <option value='Chile' />
// <option value='Iraq' />
// <option value='Thailand' />
// <option value='Sweden' />
// <option value='Romania' />
// <option value='Portugal' />
// <option value='Japan' />
// <option value='Austria' />
// <option value='Jordan' />
// <option value='Bangladesh' />
// <option value='Serbia' />
// <option value='Switzerland' />
// <option value='Nepal' />
// <option value='UAE' />
// <option value='Lebanon' />
// <option value='Tunisia' />
// <option value='Oman' />
// <option value='Saudi-Arabia' />
// <option value='Ecuador' />
// <option value='Bulgaria' />
// <option value='Panama' />
// <option value='Costa-Rica' />
// <option value='Croatia' />
// <option value='Kuwait' />
// <option value='Uruguay' />
// <option value='Azerbaijan' />
// <option value='Slovakia' />
// <option value='Dominican-Republic' />
// <option value='Palestine' />
// <option value='Denmark' />
// <option value='Ireland' />
// <option value='Sri-Lanka' />
// <option value='Malaysia' />
// <option value='Greece' />
// <option value='Canada' />
// <option value='Paraguay' />
// <option value='Ethiopia' />
// <option value='Morocco' />
// <option value='Venezuela' />
// <option value='Netherlands' />
// <option value='Pakistan' />
// <option value='Bolivia' />
// <option value='Honduras' />
// <option value='Kazakhstan' />
// <option value='India' />
// <option value='Ukraine' />
// <option value='Brazil' />
// <option value='Turkey' />
// <option value='UK' />
// <option value='Argentina' />
// <option value='Colombia' />
// <option value='Italy' />
// <option value='Iran' />
// <option value='Indonesia' />
// <option value='North-America' />
// <option value='South-Africa' />
// <option value='Peru' />
// <option value='Russia' />
// <option value='Poland' />
// <option value='Asia' />
// <option value='Africa' />
// <option value='Europe' />
// <option value='All' />
// <option value='Spain' />
// <option value='USA' />
// <option value='South-America' />
// <option value='Oceania' />
// <option value='France' />
// <option value='Mexico' />
// <option value='Germany' />
// <option value='MS-Zaandam-' />
// <option value='Diamond-Princess-' />
// <option value='US-Virgin-Islands' />
// <option value='Puerto-Rico' />
// <option value='Guam' />
